### ISSUE TITLE
Shard connecting is still timing out

### ISSUE THREAD

**Issue by th0mk** [xXBuilderBXx/DNetPlus#1]
First of all, thank you so much for making this package. I really appreciate it, some of these issues have really become a pain and its nice to finally have a solution.

My bot currently has 12 shards and while your fix for timeouts during connecting already reduced the startup time from 6 to 4 minutes and greatly reduces the amount of disconnections, it still timeouts on shard 5-11. Is there anything else I should do?
You can view my startup here: https://github.com/fmbot-discord/fmbot/blob/dev/src/FMBot.Bot/Services/StartupService.cs#L47

**Comment by xXBuilderBXx** [comment]
Intresting i have a 33 shards bot that is not getting any timeouts, is the timeouts happening on startup or if it's been on for a few hours

**Comment by th0mk** [comment]
Only on startup, it looks like they all start connecting at the same time and only the first few can connect without timing out.

**Comment by xXBuilderBXx** [comment]
I also had the issue with my bot and made a nice workaround for it.
Instead of await this._client.StartAsync();
You would add a delay for each connection
foreach(var shard in _client.Shards)
{
   await shard.StartAsync();
   await Task.Delay(3000);
}
This would start each shard normally but with a delay to prevent timeouts this is because the API limits shard connections and the lib does not handle it well.

There is also a pull request on the Discord.net repo #1537 that apparently solves some of this but i need to test it.

**Comment by xXBuilderBXx** [comment]
Also i have added some methods to set status and game on StartAsync see https://github.com/xXBuilderBXx/DNetPlus/commit/15c23b2f70ffcaa8985b5a980832e57dd489f8f1

**Comment by th0mk** [comment]
Thanks, I used your code but with a little more delay (`6000` instead of `3000`) and it works perfectly. Thank you.
