### ISSUE TITLE
Discord.Net.Rest available?

### ISSUE THREAD

**Issue by th0mk** [xXBuilderBXx/DNetPlus#2]
Hi, I need to use `context.Client.Rest.GetUserAsync` since `context.Guild.GetUserAsync()` only returns users from cache, and due to the recent Discord changes there don't seem to be any users in here anymore except the one that requested the command.

Would you be able to publish the Rest package from Discord.Net as well?

**Comment by xXBuilderBXx** [comment]
That's already in it but you can't normally access from Context.Client probably because it's casted to a SocketDiscordClient try accessing the Program._Client if you have it static or using dependeny injection into the module to get the IDiscordClient.
I will look into adding an extension method the fix this.

**Comment by xXBuilderBXx** [comment]
Added an extension method for Context.Client.Rest() to get the rest client and should work with sharded context/client too.

**Comment by xXBuilderBXx** [comment]
Hey i would like to let you know that just now i have created a custom docs website for DNetPlus which you can view here https://docs.discordservices.net/dnetplus
It has a big list of tweaks with a description and example.
Some of the tweaks are missing an example and will be added later on.
